# This file is part of inenv.
# https://github.com/pnegahdar/inenv

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Parham Negahdar <pnegahdar@gmail.com>

language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
